apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "integration.backend.fullname" . }}
  labels:
    {{- include "integration.backend.labels" . | nindent 4 }}
  annotations:
    timestamp: "{{ ((now).Unix) }}"
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "integration.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "integration.backend.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "integration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "integration.backend.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.backend.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLOUD_TYPE
              value: "{{ .Values.cloudType }}"
            - name: PORT
              value: "80"
            - name: VITE_APP_BACKEND_URL
              value: "{{ .Values.backend.appBackendURL }}"              
            - name: FIELDAP_API_BASE_URL
              value: "{{ .Values.backend.backendHostname }}"
            - name: LOGGING_LEVEL
              value: "{{ .Values.backend.loggingLevel }}"
            - name: SENTRY_DSN
              value: "{{ .Values.backend.sentryDSN }}"
            - name: K8S_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_POD_RELEASE
              value: "{{ .Values.backend.release }}"
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 30
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
    #     readinessProbe: # Not required - the backend is always ready if it is live
    #   {{- with .Values.nodeSelector }}
    #   nodeSelector:
    #     {{- toYaml . | nindent 8 }}
    #   {{- end }}
    # {{- with .Values.affinity }}
    #   affinity:
    #     {{- toYaml . | nindent 8 }}
    # {{- end }}
    # {{- with .Values.tolerations }}
    #   tolerations:
    #     {{- toYaml . | nindent 8 }}
    # {{- end }}
