{{- if .Values.backend.ingress.enabled -}}
{{- $fullName := include "integration.backend.fullname" . -}}

{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ if not .Values.noenforcehttps }}
{{- if .Values.backend.ingress.tls }}
  tls:
  {{- range .Values.backend.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- else }}
  tls:
    - {}
{{- end }}
{{- end }}
  rules:
    - host: {{ template "integration.backend.hostname" . }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80
  {{- if .Values.backend.ingress.hosts }}
    {{- range .Values.backend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - pathType: Prefix
            path: {{ . }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80
        {{- end }}
    {{- end }}
  {{- end }}

{{- else -}}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "integration.backend.labels" . | nindent 4 }}
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.backend.ingress.tls }}
  tls:
  {{- range .Values.backend.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- else }}
  tls:
    - {}
{{- end }}
  rules:
    - host: {{ template "integration.backend.hostname" . }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- if .Values.backend.ingress.hosts }}
    {{- range .Values.backend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
        {{- end }}
    {{- end }}
  {{- end }}

{{- end }}
{{- end }}
