{{- if .Values.frontendvue.ingress.enabled -}}
{{- $fullName := include "integration.frontendvue.fullname" . -}}

{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "integration.frontendvue.labels" . | nindent 4 }}
  {{- with .Values.frontendvue.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.frontendvue.ingress.tls }}
  tls:
  {{- range .Values.frontendvue.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- else }}
  tls:
    - {}
{{- end }}
  rules:
    - host: {{ template "integration.frontendvue.hostname" . }}
      http:
        paths:
          - path:
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- if .Values.frontendvue.ingress.hosts }}  
    {{- range .Values.frontendvue.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
