apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "integration.frontendsvelte.fullname" . }}
  labels:
    {{- include "integration.frontendsvelte.labels" . | nindent 4 }}
  annotations:
    timestamp: "{{ ((now).Unix) }}"
spec:
  replicas: {{ .Values.frontendsvelte.replicaCount }}
  selector:
    matchLabels:
      {{- include "integration.frontendsvelte.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "integration.frontendsvelte.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
    {{- end }}
      serviceAccountName: {{ include "integration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "integration.frontendsvelte.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{.Values.frontendsvelte.image.name}}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VITE_APP_BACKEND_URL
              value: "{{ .Values.backend.appBackendURL }}"
            - name: VITE_FIELDAP_API_BASE_URL
              value: "{{ .Values.backend.backendHostname }}"
          resources:
            {{- toYaml .Values.frontendsvelte.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /index.html
              port: http
            periodSeconds: 30
            initialDelaySeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
    #   {{- with .Values.nodeSelector }}
    #   nodeSelector:
    #     {{- toYaml . | nindent 8 }}
    #   {{- end }}
    # {{- with .Values.affinity }}
    #   affinity:
    #     {{- toYaml . | nindent 8 }}
    # {{- end }}
    # {{- with .Values.tolerations }}
    #   tolerations:
    #     {{- toYaml . | nindent 8 }}
    # {{- end }}
