apiVersion: v1
kind: Service
metadata:
  name: {{ include "integration.frontendvue.fullname" . }}
  labels:
    {{- include "integration.frontendvue.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontendvue.service.type }}
  ports:
    - port: {{ .Values.frontendvue.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "integration.frontendvue.selectorLabels" . | nindent 4 }}
